name: CD - Deploy Pokedex

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to Production
    runs-on: self-hosted

    steps:
      - name: Executing remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Define project path
            PROJECT_PATH="/home/${{ secrets.SERVER_USER }}/pokedex"
            
            # Ensure the directory exists
            if [ ! -d "$PROJECT_PATH" ]; then
              echo "Project directory not found. Cloning repository..."
              git clone https://github.com/jitterbit/pokedex.git "$PROJECT_PATH"
            fi

            # Navigate to project folder
            cd "$PROJECT_PATH"
            
            # Fetch latest version
            git fetch origin main
            git reset --hard origin/main
            
            # Rebuild and start containers using docker-compose
            # -d: Detached mode
            # --build: Rebuild images before starting
            docker-compose up -d --build
            
            # Clean up old images (Dangling images) to save space
            docker image prune -f
